[package]
name = "type-proof"
version = "0.1.0"
description = "A crate for type-checked propositional logic proofs"
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
type-proof-macros = { path = "../type-proof-macros", version = "0.1.0" }
