[package]
name = "type-proof-macros"
version = "0.1.0"
description = "Macros for the type-proof crate"
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0.106"
quote = "1.0.41"

[dev-dependencies]
type-proof = { path = "../type-proof" }
